id: P004279
initial_creation_type: ocr
source_metadata:
  id: bdr:W22151
  title: ཆེད་རྩོམ་གསེར་གྱི་ཐང་མ། བོད་ལུགས་གསོ་རིག
  author: ''
  volumes:
    c8f538ddfe0a46a59d425b36e466ca09:
      image_group_id: I1PD28106
      title: ''
      volume_number: 1
      total_pages: 262
      base_file: v001.txt
